FBForUs/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'FBForUs'

urlpatterns = [
    # 로그인, 로그아웃, 회원가입
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),

    # 축구소식
    path('news_create/', views.news_create, name='news_create'),
    path('newslist/', views.news_list, name='news_list'),
    path('<int:news_id>/', views.news_detail, name='news_detail'),

    # 마이페이지
    path('userlist/', views.user_list, name='user_list'),
    path('userlist/delete/<int:news_id>/', views.user_delete, name='user_delete'),

    # 축구소식 검색
    path('search/', views.news_search, name='news_search'),

    # 축구소식 수정, 삭제
    path('news/modify/<int:news_id>/', views.news_modify, name='news_modify'),
    path('news/delete/<int:news_id>/', views.news_delete, name='news_delete'),


    # 축구소식 댓글
    path('comment/create/<int:news_id>/', views.comment_create, name='comment_create'),

    # 축구소식 댓글 수정, 삭제
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),

    # 대댓글
    path('reply/create/<int:comment_id>/', views.reply_create, name='reply_create'),

    # 대댓글 수정, 삭제
    path('reply/modify/<int:reply_id>/', views.reply_modify, name='reply_modify'),
    path('reply/delete/<int:reply_id>/', views.reply_delete, name='reply_delete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FootballForUs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('FBForUs/', include('FBForUs.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #넣어야지 업로드된 파일을 URL 로 업데이트됩니다.

FBForUs/models.py
from django.db import models
from django.contrib.auth.models import User

class News(models.Model) :
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_news')
    title = models.CharField(max_length=100, null=False)
    content_image = models.ImageField(upload_to='images/%Y/%m/%d', null=True, blank=True)
    content = models.TextField(null=False)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.title

class Comment(models.Model) :
    news = models.ForeignKey(News, null=True, blank=True, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.content

class Reply(models.Model) :
    comment = models.ForeignKey(Comment, null=True, blank= True, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return '댓글 {}의 대댓글 :{}'.format(self.comment, self.content)

FBForUs/forms.py
from django import forms
from .models import News, Comment, Reply

class RegisterForm(forms.Form) :
    email = forms.EmailField(label='이메일', error_messages={'invalid' : '유효한 이메일 주소를 입력해주세요.'})
    password = forms.CharField(label='비밀번호', min_length=6, max_length=20, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='비밀번호 확인', min_length=6, max_length=20, widget=forms.PasswordInput)
    fullname = forms.CharField(label='이름', min_length=2, max_length=5)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()

        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password != password_confirm :
            raise forms.ValidationError({
                "password_confirm" : ["2개의 비밀번호가 일치하지 않습니다."]
            })

        return cleaned_data
    #clean 함수의 return 값은 무조건 cleaned_data를 꼭 해줘야함

class LoginForm(forms.Form) :
    email = forms.EmailField(label='이메일', error_messages={'invalid': '유효한 이메일 주소를 입력해주세요.'})
    password = forms.CharField(label='비밀번호', min_length=6, max_length=20, widget=forms.PasswordInput,
                               error_messages={'invalid':'비밀번호가 일치하지 않습니다.'})

class NewsForm(forms.ModelForm) :
    class Meta :
        model = News
        fields = ['title', 'content_image', 'content']
        labels = {
            'title' : '제목',
            'content' : '내용',
            'content_image' : '소식 첨부파일'
        }

class CommentForm(forms.ModelForm) :
    class Meta :
        model = Comment
        fields = ['content']
        labels = {
            'content' : '댓글 내용'
        }

class ReplyForm(forms.ModelForm) :
    class Meta :
        model = Reply
        fields = ['content']
        labels = {
            'content' : '대댓글 내용'
        }

FBForUs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth, messages
from .forms import LoginForm, RegisterForm, NewsForm, CommentForm, ReplyForm
from django.utils import timezone
from django.contrib.auth.models import User #유저 데이터 저장을 위해 선언
from .models import News, Comment, Reply
from django.core.paginator import Paginator

#로그인, 로그아웃, 회원가입

def login(request) :
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = auth.authenticate(username=email, password=password)
            if user:
                auth.login(request, user)
                return redirect('FBForUs:news_list')
            else :
                messages.error(request, '아이디 또는 비밀번호가 틀렸습니다!')
    else:
        form = LoginForm()
    context = {
        'form': form
    }
    return render(request, 'pages/login.html', context)

def logout(request) :
    auth.logout(request)
    return redirect('/FBForUs')

def signup(request) :
    if request.method == 'POST' :
        form = RegisterForm(request.POST)
        if form.is_valid() :
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            if User.objects.filter(email=request.POST['email']).exists():
                messages.error(request, '사용 중인 아이디 입니다.')
                return render(request, 'pages/signup.html')
            else :
                User.objects.create_user(email, email, password)
                messages.success(request, '회원가입이 성공적으로 완료되었습니다!')
            return redirect('FBForUs:login')
    else :
        form = RegisterForm()
    context = {
        'form' : form
    }
    return render(request, 'pages/signup.html', context)

# 축구 소식 news
def news_create(request) :
    if request.method == 'POST':
        form = NewsForm(request.POST)
        if form.is_valid():
            news = form.save(commit=False)
            try :
                news.content_image = request.FILES["content_image"]
            except :
                pass
            news.create_date = timezone.now()
            news.author = request.user
            news.save()
            return redirect('FBForUs:news_list')
    else:
        form = NewsForm()
    context = {
        'form': form
    }
    return render(request, 'pages/news_create.html', context)

def news_modify(request, news_id) :
    news = get_object_or_404(News, pk=news_id)
    if request.method == "POST" :
        form = NewsForm(request.POST, request.FILES, instance=news)
        if form.is_valid() :
            news = form.save(commit=False)
            news.author = request.user
            news.modify_date = timezone.now()
            try :
                news.content_image = request.FILES["content_image"]
            except :
                pass
            news.save()
            return redirect('FBForUs:news_detail', news_id=news.id)
    else :
        form = NewsForm(instance=news)
    context = {
        'form' : form
    }
    return render(request, 'pages/news_create.html', context)

def news_delete(request, news_id) :
    news = News.objects.get(id=news_id)
    news.delete()
    return redirect('FBForUs:news_list')

max_list_count = 12
max_page_count = 10

def news_list(request) :
    page = request.GET.get('page', 1)
    news_list = News.objects.order_by('-create_date')
    paginator = Paginator(news_list, max_list_count)
    page_obj = paginator.get_page(page)

    # 전체 페이지 마지막 번호
    last_page_num = 0

    for last_page_num in paginator.page_range:
        last_page_num = last_page_num + 1

    # 현재 페이지가 몇번째 블럭인지
    current_block = (( int(page) - 1 ) / max_page_count ) + 1
    current_block = int(current_block)

    # 페이지 시작번호
    page_start_number = ((current_block - 1) * max_page_count) + 1

    # 페이지 끝 번호
    page_end_number = page_start_number + max_page_count - 1

    context = {
        'news_list' : page_obj,
        'last_page_num' : last_page_num,
        'page_start_number' : page_start_number,
        'page_end_number' : page_end_number
    }
    return render(request, 'pages/news_list.html', context)

def user_list(request) :
    page = request.GET.get('page', 1)
    news_list = News.objects.order_by('-create_date')
    paginator = Paginator(news_list, max_list_count)
    page_obj = paginator.get_page(page)

    # 전체 페이지 마지막 번호
    last_page_num = 0

    for last_page_num in paginator.page_range:
        last_page_num = last_page_num + 1

    # 현재 페이지가 몇번째 블럭인지
    current_block = ((int(page) - 1) / max_page_count) + 1
    current_block = int(current_block)

    # 페이지 시작번호
    page_start_number = ((current_block - 1) * max_page_count) + 1

    # 페이지 끝 번호
    page_end_number = page_start_number + max_page_count - 1

    context = {
        'news_list': page_obj,
        'last_page_num': last_page_num,
        'page_start_number': page_start_number,
        'page_end_number': page_end_number
    }
    return render(request, 'pages/user_list.html', context)

def user_delete(request, news_id) :
    news = News.objects.get(id=news_id)
    news.delete()
    return redirect('FBForUs:user_list')

def news_search(request) :
    news = News.objects.all().order_by('-create_date')
    q = request.POST.get('q', '')

    if q:
        news = news.filter(title__icontains=q)
        return render(request, 'pages/news_search.html', {'news': news, 'q': q})

    else:
        return render(request, 'pages/news_search.html')

def news_detail(request, news_id) :
    # news = News.objects.get(id=news_id)
    news =  get_object_or_404(News, pk=news_id)
    try :
        news.content_image = request.FILES["news.content_image"]
        context = {'news': news, 'news.content_image': news.content_image}
    except :
        pass
        context = { 'news' : news }
    return render(request, 'pages/news_detail.html', context)

# 축구 소식 comment
def comment_create(request, news_id) :
    news = get_object_or_404(News, pk=news_id)
    # news = News.objects.get(id=news_id)
    if request.method == "POST" :
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid() :
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.news = news
            comment.save()
            return redirect('FBForUs:news_detail', news_id=news.id)
        else :
            messages.warning(request, '반드시 1글자 이상 기입해주세요.')
    else :
        comment_form = CommentForm()
    context = {
        'comment_form' : comment_form, 'news' : news
    }
    return render(request, 'pages/news_detail.html', context)

def comment_modify(request, comment_id) :
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == 'POST' :
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid() :
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('FBForUs:news_detail', news_id=comment.news.id)
    else :
        form = CommentForm(instance=comment)
    context = {
        'form' : form, 'comment' : comment
    }
    return render(request, 'pages/comment_modify.html', context)

def comment_delete(request, comment_id) :
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return redirect('FBForUs:news_detail', news_id=comment.news.id)

def reply_create(request, comment_id) :
    # news = get_object_or_404(News, pk=news_id)
    comment = get_object_or_404(Comment, pk=comment_id)
    # comment = Comment.objects.get(id=comment_id)
    if request.method == "POST" :
        form = ReplyForm(request.POST)
        if form.is_valid() :
            reply = form.save(commit=False)
            reply.author = request.user
            reply.create_date = timezone.now()
            reply.comment = comment
            reply.save()
            return redirect('FBForUs:news_detail', news_id=reply.comment.news.id)
    else :
        form = ReplyForm()
    context = {
        'form' : form
    }
    return render(request, 'pages/reply_form.html', context)

def reply_modify(request, reply_id) :
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.method == "POST" :
        form = ReplyForm(request.POST, instance=reply)
        if form.is_valid() :
            reply = form.save(commit=False)
            reply.modify_date = timezone.now()
            reply.save()
            return redirect('FBForUs:news_detail', news_id = reply.comment.news.id)
    else :
        form = ReplyForm(instance=reply)
    context = {
        'form' : form
    }
    return render(request, 'pages/reply_form.html', context)

def reply_delete(request, reply_id) :
    reply = get_object_or_404(Reply, pk=reply_id)
    reply.delete()
    return redirect('FBForUs:news_detail', news_id = reply.comment.news.id)

FBForUs/templates/form_errors.html
{% if form.errors %}
      {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
      {% endfor %}
{% endif %}

FBForUs/templates/navbar.html
<!-- 로그인 후 navbar -->
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
    <a class="navbar-brand ms-4" href="{% url 'FBForUs:news_list' %}">FootBall For Us</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse justify-content-end me-4">
            <ul class="navbar-nav nav-taps">
                <li class="nav-item">
                    <a class="nav-link btn-outline-info" href="{% url 'FBForUs:user_list' %}">
                        <span class="text-primary">{{ user.username }}</span> 님</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn-outline-info" href="{% url 'FBForUs:logout' %}">로그아웃</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn-outline-info" href="{% url 'FBForUs:news_list' %}">축구 소식</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- 로그인 전 navbar -->
{% else %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
    <a class="navbar-brand ms-4" href="{% url 'FBForUs:login' %}">FootBall For Us</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse justify-content-end me-4">
            <ul class="navbar-nav nav-taps">
                <li class="nav-item me-4">
                    <a class="nav-link btn-outline-info" href="{% url 'FBForUs:login' %}">LOGIN</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn-outline-info" href="{% url 'FBForUs:signup' %}">SIGN UP</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endif %}

FBForUs/templates/paginator.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FootBall For Us</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'news_list.css' %}">
</head>
<body>
    {% if news_list %}
        <ul class="pagination justify-content-center">
        <!--이전 페이지-->
            {% if news_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">
                    이전
                </a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">이전</a></li>
            {% endif %}
            <!--페이지 링크 처리 -->
            {% for page_number in news_list.paginator.page_range %}
            {% if page_start_number <= page_number|add:5 and page_start_number >= page_number|add:-5 %}
                {% if page_number == news_list.number %}
                    <li class="page-item active"><a class="page-link" href="#">{{ page_number }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
                {% endif %}
            {% endif %}
            {% endfor %}
            <!-- 다음 페이지 -->
            {% if news_list.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ last_page_num }}">다음</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#"> 다음 </a></li>
            {% endif %}
        </ul>
    {% endif %}

</body>